//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agency
    {
        public long AgencyID { get; set; }
        public string AgencyName { get; set; }
    }
}
